<?php

namespace AppBundle\Repository;

/**
 * AtributoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoRepository extends \Doctrine\ORM\EntityRepository
{
}
