<?php

namespace AppBundle\Repository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComponentesHijos()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Componente c WHERE c.padre IS NOT NULL')
            ->getResult();
    }

    public function getComponentesPadres()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Componente c WHERE c.padre IS NULL')
            ->getResult();
    }
}
