<?php

namespace AppBundle\Repository;

/**
 * OperacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperacionRepository extends \Doctrine\ORM\EntityRepository
{
}
