<?php

namespace AppBundle\Repository;

/**
 * RecursoAtributoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecursoAtributoRepository extends \Doctrine\ORM\EntityRepository
{
}
