security:
        encoders:
            FOS\UserBundle\Model\UserInterface: sha512

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

        providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email

        firewalls:
            main:
                remember_me:
                    secret:   '%secret%'
                    lifetime: 2592000 # 1 mes en segundos
                    path:     /

                pattern: ^/

                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check
                    default_target_path: /

                logout:
                    path:   fos_user_security_logout
                    target: inicio

                anonymous:    true
                
        access_control:
            - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: fos_user_registration_register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: fos_user_resetting_request, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: ROLE_USER }